### ISSUE TITLE
npm i

### ISSUE THREAD

**Issue by jj-apm** [LaoLeo/club-RESTful#1]
npm i出错了

**Comment by LaoLeo** [comment]
> npm i出错了

贴下报错信息，详细点

**Comment by jj-apm** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AlexL"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 中午11:43
收件人:&nbsp;"LaoLeo/club-RESTful"<club-RESTful@noreply.github.com&gt;;
抄送:&nbsp;"github小程序同学"<1431105276@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LaoLeo/club-RESTful] npm i (#1)



 
npm i出错了
  
贴下报错信息，详细点
 
—就是微信开发者导入的的时候，

**Comment by jj-apm** [comment]
> > npm i出错了
> 
> 贴下报错信息，详细点

![image](https://user-images.githubusercontent.com/44701261/70406035-438f0480-1a7a-11ea-8b7d-bb599116f859.png)

**Comment by jj-apm** [comment]
> > npm i出错了
> 
> 贴下报错信息，详细点
微信开发者工具导入的时候说请选择含有app.json/project.conf.json的目录
